Add Charlot Shaw's paper
UMM-CSci/senior-seminar pull request #46
Opened 2021-04-05 20:23 UTC by UnwarySage

I'm working on improving my resume, and would like an official spot to link to when I discuss my seminar.
I don't have the Ruby toolchain installed, so can't verify that this builds, but I believe it should.
Thanks in advance,
Charlot

2021-04-05 21:45 UTC, floogulinc requested changes
I would ask you to please use the same naming convention we use for the other seminars. Your paper should be `shaw.pdf` and your slides `shawslides.pdf`

2021-04-06 00:37 UTC, UnwarySage commented
Have done so

2021-04-06 01:16 UTC, floogulinc requested changes

2021-04-06 01:16 UTC, floogulinc commented on _seminars/spring2020/index.md
> +    slides: ShawSlides.pdf
You need to update the list too.

```suggestion
    pdf: shaw.pdf
    slides: shawslides.pdf
```

2021-04-06 01:19 UTC, floogulinc commented
Oh also, even if you don't have all the Ruby stuff installed you can easily build and preview the site locally with Docker. This is from the README:

<blockquote>

### Running with Docker

If you have Docker you can run the site with docker using

```bash
docker run -it --rm -v ${PWD}:/usr/src/app -p 4000:4000 starefossen/github-pages
```

This will serve the site on port 4000 (it should also automatically rebuild the site when changes are made to the files).

</blockquote>

2021-04-06 02:02 UTC, UnwarySage commented
Realized the `index.md` needed to be updated as well, unfortunately after pushing.

2021-04-06 02:19 UTC, floogulinc requested changes

2021-04-06 02:19 UTC, floogulinc commented on _seminars/spring2020/index.md
> +    pdf: shawseminar.pdf
This is still incorrect.

```suggestion
    pdf: shaw.pdf
```

2021-04-18 02:58 UTC, UnwarySage commented
I believe I've settled the outstanding issues.
Do you see anything else on your end?

2021-04-18 03:00 UTC, merged